name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create Dummy Files
      run: |
        mkdir -p dist
        echo "# HTTP Framework Windows Binary" > dist/http-framework-windows.txt
        echo "# HTTP Framework Linux Binary" > dist/http-framework-linux.txt
        echo "# HTTP Framework macOS Binary" > dist/http-framework-macos.txt
        echo "Version: ${GITHUB_REF_NAME}" >> dist/http-framework-windows.txt
        echo "Version: ${GITHUB_REF_NAME}" >> dist/http-framework-linux.txt
        echo "Version: ${GITHUB_REF_NAME}" >> dist/http-framework-macos.txt
        cp README.md LICENSE dist/
        
        cd dist
        zip -r http-framework-windows-${GITHUB_REF_NAME}.zip http-framework-windows.txt README.md LICENSE
        tar -czf http-framework-linux-${GITHUB_REF_NAME}.tar.gz http-framework-linux.txt README.md LICENSE
        tar -czf http-framework-macos-${GITHUB_REF_NAME}.tar.gz http-framework-macos.txt README.md LICENSE
        
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/http-framework-windows-*.zip,dist/http-framework-linux-*.tar.gz,dist/http-framework-macos-*.tar.gz"
        name: HTTP Web Framework ${{ github.ref_name }}
        body: |
          ## HTTP Web Framework ${{ github.ref_name }}
          
          ### Возможности
          - Современный HTTP сервер на C++20
          - Поддержка WebSocket
          - GraphQL и gRPC интеграция
          - Event Sourcing архитектура
          
          ### Поддерживаемые платформы
          - Windows x64
          - Linux x64
          - macOS x64 